sudo: required

language: cpp

matrix:
  include:
    - os: linux
      services: docker
      before_install: 
        - docker pull glportal/whale-gcc:coverall
      script:
        - docker run -it --rm -w /data -v $(pwd):/data glportal/whale-gcc:coverall bash -c "cmake -DCOVERAGE:BOOL=ON ./&& make && make tests;"
        - ls -la
        - ls -la docroot

