sudo: required

language: cpp

matrix:
  include:
    - os: linux
      services: docker
      before_install: 
        - docker pull glportal/whale-gcc:coverall
        - pip install --user cpp-coveralls
      script:
        - docker run -it --rm -w /data -v $(pwd):/data glportal/whale-gcc:coverall bash -c "cmake -DCOVERAGE:BOOL=ON ./&& make && make tests && ctest && ctest;"
        - coveralls -i include -i source -e tests --gcov-options \'-lp\'
        - find . -iname '*.gcda' | wc -l
        - find . -iname '*.gcno' | wc -l
        - grep -Rni 'coverage' CMakeFiles/* | wc -l
